apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - args:
        - bash
        - -c
        - cd /application && npm run dev
        image: rajendar1rana/demo-marn-backend:original
        imagePullPolicy: ""
        name: backend
        ports:
        - containerPort: 3003
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
